[CFRS-101] 소속 검색 기능 구현
Foundy-LLC/camstudy-web pull request #42
Opened 2023-02-20 05:43 UTC by kgunwoo26

### 상세 내용
- 소속명에 입력 시 유사한 소속명을 출력
- 추천 소속명을 클릭 시 input에 입력된 값을 그 값으로 바꿈.

디바운스를 추가만 하면 입력 값이 undefined 라는 에러가 떠서 추가를 못했습니다. 추후에 해결해서 추가해서 올리도록 하겠습니다

2023-02-20 08:06 UTC, jja08111 requested changes
고생하셨습니다! 의견남길게용

2023-02-20 08:06 UTC, jja08111 commented on src/utils/organizations.validator.ts
> +    throw `긴 휴식 주기는 ${POMODORO_LONG_INTERVAL_RANGE}회 사이만 가능합니다.`;
메시지가 잘못되었네요.

2023-02-20 08:06 UTC, jja08111 commented on src/stores/OrganizationStore.tsx
> +    console.log("이름", name);
디버그용 로그들은 제거해주세요

2023-02-20 08:06 UTC, jja08111 commented on src/stores/OrganizationStore.tsx
> +  //TODO 리액트 디바운스 (0.5s)
구현된 TODO 주석은 지워주세요

2023-02-20 08:06 UTC, jja08111 commented on src/controller/organization.controller.ts
> +    const organizationsGetBody = separateOrganizationsRequests(req.query);
OrganizationsGetRequestBody와 OrganizationsSearchRequestBody로 나누지 않고도 API를 구현할 수 있을 것 같아요.
OrganizationsGetRequestBody 하나만 두고 여기에 두개의 변수를 가지도록 하는게 나아보입니다. 
```typescript
query: string?
page: number
```

그리고 query가 존재할 때만 `where`절에 `{ name: { startsWith: RequestBody.name } },`을 삽입하면 될것 같습니다.

2023-02-20 08:06 UTC, jja08111 commented on src/repository/organization.repository.ts
> +      where: { name: { startsWith: RequestBody.name } },
skip과 take가 빠졌네요. 이런경우 모든 값을 전부 가져와서 리소스 낭비가 될것같아요. 

앞선 코멘트에서 query 유무에 따라 where절을 넣으면 되니 if 조건 없이 더 단순화할 수 있어보입니다.

2023-02-20 08:34 UTC, kgunwoo26 commented on src/controller/organization.controller.ts
> +    const organizationsGetBody = separateOrganizationsRequests(req.query);
유사 학교/회사명 검색할 땐 page 값이 필요없고, 조회할 땐 query(name) 값이 필요가 없을 것 같아서 이렇게 했습니다 ! 그래도 둘다 합치는게 나을까요 ?

2023-02-20 11:06 UTC, jja08111 commented on src/controller/organization.controller.ts
> +    const organizationsGetBody = separateOrganizationsRequests(req.query);
@kgunwoo26 넵 합치는게 단순할것같아요~! 쿼리가 있으면 해당 쿼리와 일치하는 유사 학교/회사명을 필터링하고 없다면 필터링 없이 모두 보여주는 것입니다.

page는 애매하긴하네요.. 제 생각에는 백준처럼 구현한다고 가정하면, 유사 학교/회사명 조회는 기본 페이지 값(0)으로 놓고 검색을 하고 조회의 경우 해당 page을 이용하면 될것같네요.

2023-02-21 01:27 UTC, jja08111 approved these changes
LGTM

2023-02-21 01:27 UTC, merged