[CFRS-131] 친구 목록 조회
Foundy-LLC/camstudy-web pull request #68
Opened 2023-03-13 07:24 UTC by kgunwoo26

### 상세 내용
- 친구 목록 조회 버튼을 클릭하면 친구 목록을 출력
- 프로필 사진 /  이름 / 랭킹 점수 / 로그인 상태 순으로 표시

https://user-images.githubusercontent.com/56541313/224633985-4b9e48c8-ced5-4cf4-a11b-b5f2c1684373.mov

2023-03-13 11:22 UTC, jja08111 requested changes

2023-03-13 11:22 UTC, jja08111 commented on src/controller/friend.controller.ts
> +    else {
친구 요청 목록인지 친구 목록인지 page로 구분하는데 좋은방법 같지는 않네요... 친구 요청 목록 또한 페이지네이션이 필요할 수 있기 때문에 바람직하지 않습니다. 
그리고 page로 구분한다는 것 자체가 혼돈을 야기합니다. 때문에 전에 논의한대로 아예 다른 API를 만들거나 query로 구분해야겠습니다.

2023-03-14 00:12 UTC, jja08111 commented on src/controller/friend.controller.ts
> +    else {
@kgunwoo26 넵 그렇게 진행하면 좋을것같네요

2023-03-14 11:46 UTC, kgunwoo26 commented on src/controller/friend.controller.ts
> +    else {
@jja08111 수정했습니다 !

2023-03-14 12:30 UTC, jja08111 commented on src/controller/friend.controller.ts
> +    ) {
`accepted`가 undefined인 경우는 기본 값으로 true를 지정해야 할 것 같습니다. 지금은 accepted가 주어지지 않는 경우 예외를 던져 400 응답을 반환하고 있네요.

그리고 API 명세서와 일치하지 않네요. 명세서가 일치하지 않으면 안드로이드 개발이 힘들어지기 때문에 일치해주셨으면 좋겠습니다!

2023-03-14 13:37 UTC, kgunwoo26 commented on src/controller/friend.controller.ts
> +    ) {
친구 목록 조회일 경우 accepted 값에 true를 전송해서 undefined를 예외처리 했습니다. accepted가 undefined 일 경우 true로 만든다면 친구 목록 조회가 아닌 다른 예외상황에서도 accepted를 true로 만들 것 같은데 그런 경우는 문제가 안될까요 ?

2023-03-14 14:08 UTC, jja08111 commented on src/controller/friend.controller.ts
> +    ) {
@kgunwoo26 이것도 사실 구현하기 나름이긴 합니다. accepted 기본값이 있다면 쿼리없이 GET /users/{userId}/friends API를 요청하면 친구 목록이 반환될 것입니다.

혹시 친구 목록 조회가 아닌 다른 예외 상황은 어떤 상황인가요?

아 그리고 API 명세서를 다시보니 친구 요청 목록 조회랑 친구 목록 API가 아직 따로 있습니다. 지금처럼 구현한다면 친구 요청 목록 조회 API는 없애는 것이 맞고, accepted 쿼리 내용을 친구 목록 API에 두는 것이 맞습니다.

2023-03-15 01:11 UTC, kgunwoo26 commented on src/controller/friend.controller.ts
> +    ) {
수정해서 올렸습니다 !

2023-03-15 01:34 UTC, jja08111 approved these changes
LGTM

2023-03-15 04:02 UTC, merged