Initial commit
Foundy-LLC/camstudy-web pull request #7
Opened 2023-02-01 07:38 UTC by Antonio-990510

## 작업 개요
- 구글 로그인
- 프로필 생성 API 생성
## 상세 내용
- 태그 테이블에 저장 할 때 중복을 피하기 위해 태그 name을 유니크 키로 생성 후 아래 구문을 통해 해결
```javascript
const tag = await prisma.tag.createMany({
          data: [...arr],
          skipDuplicates: true,
        });
```
- 태그 테이블에 저장 후 태그 이름으로 태그 아이디 찾아서 유저 테이블, 유저 태그 테이블 생성

2023-02-01 08:16 UTC, kgunwoo26 commented on src/pages/welcome.tsx
> +  const onChange = (e: any) => {
"<>"때문에 그런지 글씨가 잘려서 이렇게 씁니다

2023-02-01 09:54 UTC, Antonio-990510 commented on src/pages/welcome.tsx
> +  const onChange = (e: any) => {
반영하겠습니다.

2023-02-01 09:54 UTC, Antonio-990510 commented on src/constants/message.ts
> +export const setProfileMsg = {
응답 메세지 또한 상수라고 생각해서 따로 뺐습니다.
수정에 유리할 것 같습니다.

2023-02-01 09:55 UTC, Antonio-990510 commented on src/pages/api/users/[userId].ts
> +    case "PUT":
반영하겠습니다.

2023-02-01 10:39 UTC, jja08111 reviewed
PR 제목은 우리끼리 정한 컨벤션을 준수하도록 합시다~!
```console
PR 이름에는 다음과 같은 컨벤션(ex: [CFRS-45] 로그인 안되던 문제 수정)
```

2023-02-01 10:43 UTC, Antonio-990510 commented on src/pages/api/users/[userId].ts
> +      try {
지금 상황에서는 통째로 예외처리 해도 상관없을 것 같습니다.
반영하겠습니다.

2023-02-01 10:52 UTC, Antonio-990510 commented on src/pages/api/users/[userId].ts
> +      res.setHeader("Allow", ["GET", "PUT"]);
이 코드는 프로젝트를 만들면서 자동으로 생긴 코드인데 지우는 것을 까먹었습니다. 지우도록 하겠습니다.
setHeader의 기능은 응답을 보낼 때 헤더에 키, 값을 설정해서 보내는 역할을 합니다.
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/83750244/216022825-0e01a4d1-5ce3-49d8-bb60-c7b5b5324fff.png">
위의 이미지를 보면 Allow라는 키가 있고 값으로는 GET, PUT이 있습니다.

2023-02-01 11:17 UTC, jja08111 requested changes
로직 분리가 필요해보이네요 필요한 경우 이따 간단한 회의를 진행하겠습니다.

2023-02-01 11:17 UTC, jja08111 commented on src/constants/message.ts
> +export const setProfileMsg = {
상수이기 때문에 대문자 + _ 로 통일하는게 좋을 것 같네용. 그리고 코드는 포함해도되고 안해도 되고 하기 나름일것같습니다.
```
export const PROFILE_CREATE_SUCCESS = "프로필이 생성되었습니다."
export const NO_NAME_OR_TAG_ERROR = "이름 혹은 태그가 없습니다. 이름과 태그는 필수 항목입니다."
```

2023-02-01 11:17 UTC, jja08111 commented on src/pages/api/users/[userId].ts
> +                console.log(response);
여기 보면 모든 로직이 존재하네요. 이렇게 하기보다는 컨트롤러에서 함수를 따로 빼서 작성하는게 테스트하기에도 좋고 관리 측면에서도 유리할 것 같습니다. 
아래의 레파지토리를 참고하면 될것같네요. export는 아래의 예제처럼 하기보다 함수를 하나하나 만들고 export해도 좋습니다.
https://github.com/basemkhirat/express-mvc/blob/master/app/controllers/UserController.js

2023-02-01 11:17 UTC, jja08111 commented on src/pages/welcome.tsx
> +    });
API 요청하는 코드가 뷰에 존재하네요. 이러한 로직은 service와 같은 파일에 분리하는게 유지보수와 테스트하기 좋습니다.

2023-02-01 11:17 UTC, jja08111 commented on src/pages/welcome.tsx
> +  const [tags, setTags] = useState("");
모든 상태가 뷰에 존재하네요. 이렇게 된다면 추후에 코드가 점점 커지는 경우 관리하기 어렵습니다. 이보다 store 파일을 만들어 mobx를 이용해 상태관리를 하면 좋습니다. 하나의 클래스에서 모든 상태가 공급되도록 수정하는게 좋아보입니다.

2023-02-02 13:32 UTC, jja08111 approved these changes

2023-02-02 13:33 UTC, merged